[package]
name = "rust_c3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kd-tree = "0.5.1"
kolor = "0.1.8"
ndarray = "0.15.6"
serde_json = "1.0.96"
typenum = "1.16.0"
